import React, { useEffect } from 'react';
import { ArrowLeft } from 'lucide-react';

interface LegalProps {
  onBack: () => void;
  type: 'privacy' | 'terms';
}

export default function Legal({ onBack, type }: LegalProps) {
  useEffect(() => {
    const handleEsc = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onBack();
    };
    window.addEventListener('keydown', handleEsc);
    return () => window.removeEventListener('keydown', handleEsc);
  }, [onBack]);

  const title = type === 'privacy' ? 'Privacy Policy' : 'Terms of Service';
  const date = 'Effective Date: May 15, 2026';

  return (
    <div className="min-h-screen app-bg-container relative overflow-x-hidden font-sans pb-32 pt-10">
      <div className="app-bg animate-breathe z-0" />
      
      <div className="relative z-10 container mx-auto px-6 max-w-[800px]">
        {/* Header */}
        <button 
          onClick={onBack}
          className="flex items-center space-x-2 text-slate-500 hover:text-slate-800 transition-colors mb-12 bg-white/40 backdrop-blur-md px-4 py-2 rounded-full border border-white/50 w-fit"
        >
          <ArrowLeft className="h-4 w-4" />
          <span className="text-sm font-bold">Back</span>
        </button>

        <div className="bg-white/60 backdrop-blur-2xl border border-white/60 shadow-glass rounded-[40px] p-10 md:p-16">
          <h1 className="font-display text-[32px] md:text-[42px] font-bold tracking-tight text-[#0a1b33] mb-2">
            {title}
          </h1>
          <p className="text-sm text-slate-500 font-bold mb-10 pb-6 border-b border-slate-200">{date}</p>

          <div className="prose prose-slate max-w-none text-slate-600 leading-relaxed">
            <h2 className="font-display text-2xl font-bold text-[#0a1b33] mb-4 mt-8">1. Introduction</h2>
            <p className="mb-4">
              Welcome to ThreatLens. This {title.toLowerCase()} outlines our practices and your obligations when using our AI-driven binary security analysis platform. By accessing our services, you agree to comply with these terms.
            </p>
            
            <h2 className="font-display text-2xl font-bold text-[#0a1b33] mb-4 mt-8">2. Data Collection & Analysis</h2>
            <p className="mb-4">
              When you upload APK binaries to our platform, our Secure Compiler Engine decompiles and analyzes the contents. We do not store the original binaries permanently unless explicitly requested for threat intelligence sharing. Extractable metadata, including package names and detected vulnerabilities, may be aggregated anonymously to improve our global threat feeds.
            </p>
            
            <h2 className="font-display text-2xl font-bold text-[#0a1b33] mb-4 mt-8">3. Hardware Sandbox Isolation</h2>
            <p className="mb-4">
              Premium users utilize our Dynamic Hardware Sandbox. All executions occur within strictly isolated, ephemeral environments. We employ advanced memory tracing which may log API hooks and network traffic generated by the uploaded application solely for the purpose of generating your security report.
            </p>
            
            <h2 className="font-display text-2xl font-bold text-[#0a1b33] mb-4 mt-8">4. User Responsibilities</h2>
            <p className="mb-4">
              You must ensure you have the legal right to analyze any binary you upload to ThreatLens. Our platform is strictly for cybersecurity research, enterprise defense, and legitimate penetration testing. Any misuse of our Threat Intel APIs or decompilation engines for malicious activities will result in immediate termination of your account.
            </p>
            
            <h2 className="font-display text-2xl font-bold text-[#0a1b33] mb-4 mt-8">5. Contact Us</h2>
            <p className="mb-4">
              If you have any questions regarding this {title.toLowerCase()}, please contact our legal team at legal@threatlens.ai.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
